'''
Maximum revenue garage

Problem statement

A Garage is represented as:

struct Garage

{

int bikes;

int cars;

int trucks;

};

Implement the function

int MaxRevenue(struct Garage garages[], int m);

The function accepts an array 'garages' of type 'Garage' consisting of 'm' elements as its argument. Each element of garages consists of three non-negative integers 'bikes', 'cars' and 'trucks' referring to the count of bikes, cars and trucks in a garage respectively. The cost of servicing a bike, car and truck are 100, 250 and 500 respectively. Implement the function to calculate the revenue generated by each garage and return the maximum revenue generated. Revenue generated by garage = (100 * bikes) + (250 * cars) + (500 * trucks).

Note

1. Computed value lies within integer range

2. Return -1 if 'garages' is null(or None in the case of python)

Example1

Input

4

6 8 2

5 7 8

14 10 11

11 13 5

Output

9400

Explanation

Use revenue formula to calculate the revenue for each garage and print the maximum garage revenue.

Input format
First integer 'm' represents number of garages

Next m integers consists of three non-negative integers.

Output format
Print integer value represents maximum revenue garage.

'''

n=int(input())
arr=[]
for i in range(n):
    ele=list(map(int,input().split()))
    garage=(100*ele[0])+(250*ele[1])+(ele[2]*500)
    arr.append(garage)
print(max(arr))

